"""Single-invocation UHT code generation for all modules.

Runs UHT once on ALL modules, producing a directory tree of generated files.
Each module gets its own subdirectory: uht_gen_all/<ModuleName>/*.generated.h, *.gen.cpp

This replaces per-module uht_codegen which had cross-module type resolution issues.
"""

def _uht_codegen_all_impl(ctx):
    """Run UHT on all modules in a single invocation."""

    # Output: one directory tree for all generated files
    output_dir = ctx.actions.declare_directory("uht_gen_all")

    # Manifest: generated by the Go CLI at action time
    manifest = ctx.actions.declare_file("uht_all.uhtmanifest")

    # .uproject stub
    uproject = ctx.actions.declare_file("uht_all.uproject")
    ctx.actions.write(uproject, '{"FileVersion": 3, "EngineAssociation": "5.5", "Modules": []}')

    ctx.actions.run_shell(
        command = """
            EXECROOT=$(pwd)
            DOTNET="$EXECROOT/{dotnet}"
            UBT="$EXECROOT/{ubt}"
            GITDEPS="$EXECROOT/{gitdeps}"
            PROJECT="$EXECROOT/{project}"
            OUTPUT_DIR="$EXECROOT/{output_dir}"
            MANIFEST="$EXECROOT/{manifest}"

            # Generate multi-module manifest
            $GITDEPS uht manifest-all \\
                --registry "$EXECROOT/{registry}" \\
                --ue-source-root "$EXECROOT/{ue_source}" \\
                --output-root "$OUTPUT_DIR" \\
                --ue-root "{ue_root}" \\
                -o "$MANIFEST"

            # Run UHT from UE root
            cd {ue_root}
            "$DOTNET" "$UBT" -Mode=UnrealHeaderTool "$PROJECT" "$MANIFEST" -NoGoWide
            UHT_EXIT=$?
            if [ $UHT_EXIT -ne 0 ]; then
                echo "ERROR: UHT failed with exit code $UHT_EXIT" >&2
                cat {ue_root}/Engine/Programs/UnrealHeaderTool/Saved/Logs/UnrealHeaderTool.log >&2
                exit $UHT_EXIT
            fi
        """.format(
            dotnet = ctx.file.dotnet.path,
            ubt = ctx.file.ubt.path,
            gitdeps = ctx.executable._gitdeps.path,
            project = uproject.path,
            output_dir = output_dir.path,
            manifest = manifest.path,
            registry = ctx.file.module_registry.path,
            ue_source = ctx.file.module_registry.dirname,  # Engine/Source (where registry lives)
            ue_root = ctx.file.ubt.dirname + "/../../..",
        ),
        inputs = [ctx.file.module_registry, uproject, ctx.file.dotnet, ctx.file.ubt],
        outputs = [output_dir, manifest],
        tools = [ctx.executable._gitdeps],
        mnemonic = "UHTCodegenAll",
        progress_message = "Running UHT for all modules",
        execution_requirements = {"no-sandbox": "1"},
    )

    return [DefaultInfo(files = depset([output_dir]))]


def _uht_module_extract_impl(ctx):
    """Extract a single module's generated files from the uht_gen_all tree."""
    uht_all_dir = ctx.attr.uht_all[DefaultInfo].files.to_list()[0]
    module_dir = ctx.actions.declare_directory(ctx.attr.module_name + "_uht_gen")

    ctx.actions.run_shell(
        command = 'mkdir -p "{dst}" && if [ -d "{src}/{mod}" ]; then cp -r "{src}/{mod}/"* "{dst}/" 2>/dev/null; fi; true'.format(
            src = uht_all_dir.path,
            mod = ctx.attr.module_name,
            dst = module_dir.path,
        ),
        inputs = [uht_all_dir],
        outputs = [module_dir],
        mnemonic = "UHTModuleExtract",
        progress_message = "Extracting UHT output for %s" % ctx.attr.module_name,
    )

    return [DefaultInfo(files = depset([module_dir]))]

uht_module_extract = rule(
    implementation = _uht_module_extract_impl,
    attrs = {
        "uht_all": attr.label(mandatory = True),
        "module_name": attr.string(mandatory = True),
    },
)


uht_codegen_all = rule(
    implementation = _uht_codegen_all_impl,
    attrs = {
        "module_registry": attr.label(
            allow_single_file = [".json"],
            mandatory = True,
            doc = "Module registry JSON from buildcs-to-bazel registry command",
        ),
        "_gitdeps": attr.label(
            default = Label("//:rules_unreal_engine"),
            executable = True,
            cfg = "exec",
        ),
        "dotnet": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
        "ubt": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
    },
)
